djangoProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('learning_logs/', include('learning_logs.urls')),
]

learning_logs/urls.py
from django.urls import path
from . import views

app_name = 'learning_logs'

urlpatterns = [
    path('', views.test,name='members'),
]

learning_logs/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):
    title = models.CharField(max_length=100)
    text = models.CharField(max_length=500)
    date_add = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title

class Entry(models.Model):
    topic_id = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField(max_length=500)
    date_add = models.DateTimeField(auto_now_add=True)

    class Meta:
            verbose_name_plural = 'entries'

            def __str__(self):
                return f"{self.text[:50]}..."

learning_logs/views.py
from django.shortcuts import render
def test(request):
    return render(request,'learning_logs/index.html')

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
        ASSl
{% endblock title %}</title>
</head>
<body>
<header>
    <h1><a href="{% url 'learning_logs:members' %}">Top Fact</a></h1>
</header>
{% block body %}
{% endblock body %}

</body>
</html>

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}


{% block title %}
    Home Page
{% endblock title %}

{% block body %}
    <h2>HELLO</h2>
{% endblock body %}